/**
 * Created by admin on 6/28/2017.
 */

export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

/***** Ranking Page *****/
export const FETCHING_RANKING_DATA = 'FETCHING_RANKING_DATA';
export const FETCHING_RANKING_DATA_SUCCESS = 'FETCHING_RANKING_DATA_SUCCESS';
export const FETCHING_RANKING_DATA_FAILURE = 'FETCHING_RANKING_DATA_FAILURE';

export const FETCHING_RANKING_DATA_MORE = 'FETCHING_RANKING_DATA_MORE';
export const FETCHING_RANKING_DATA_MORE_SUCCESS = 'FETCHING_RANKING_DATA_MORE_SUCCESS';
export const FETCHING_RANKING_DATA_MORE_FAILURE = 'FETCHING_RANKING_DATA_MORE_FAILURE';

export const FETCHING_RANKING_DETAIL = 'FETCHING_RANKING_DETAIL';
export const FETCHING_RANKING_DETAIL_SUCCESS = 'FETCHING_RANKING_DETAIL_SUCCESS';
export const FETCHING_RANKING_DETAIL_FAILURE = 'FETCHING_RANKING_DETAIL_FAILURE';

export const FETCHING_RANKING_RELATED = 'FETCHING_RANKING_RELATED';
export const FETCHING_RANKING_RELATED_SUCCESS = 'FETCHING_RANKING_RELATED_SUCCESS';
export const FETCHING_RANKING_RELATED_FAILURE = 'FETCHING_RANKING_RELATED_FAILURE';

export const FETCHING_RANKING_RELATED_MORE = 'FETCHING_RANKING_RELATED_MORE';
export const FETCHING_RANKING_RELATED_MORE_SUCCESS = 'FETCHING_RANKING_RELATED_MORE_SUCCESS';
export const FETCHING_RANKING_RELATED_MORE_FAILURE = 'FETCHING_RANKING_RELATED_MORE_FAILURE';

export const SEARCH_RANKING_DATA = 'SEARCH_RANKING_DATA';
export const SEARCH_RANKING_DATA_SUCCESS = 'SEARCH_RANKING_DATA_SUCCESS';
export const SEARCH_RANKING_DATA_FAILURE = 'SEARCH_RANKING_DATA_FAILURE';

/***** User Page *****/
export const FETCHING_USER_WORKS = 'FETCHING_USER_WORKS';
export const FETCHING_USER_WORKS_SUCCESS = 'FETCHING_USER_WORKS_SUCCESS';
export const FETCHING_USER_WORKS_FAILURE = 'FETCHING_USER_WORKS_FAILURE';

/***** GIF Page *****/
export const FETCHING_GIF_DATA = 'FETCHING_GIF_DATA';
export const FETCHING_GIF_DATA_SUCCESS = 'FETCHING_GIF_DATA_SUCCESS';
export const FETCHING_GIF_DATA_FAILURE = 'FETCHING_GIF_DATA_FAILURE';
export const FETCHING_GIF_DETAIL = 'FETCHING_GIF_DETAIL';
export const FETCHING_GIF_DETAIL_SUCCESS = 'FETCHING_GIF_DETAIL_SUCCESS';
export const FETCHING_GIF_DETAIL_FAILURE = 'FETCHING_GIF_DETAIL_FAILURE';
export const FETCHING_GIF_RELATED = 'FETCHING_GIF_RELATED';
export const FETCHING_GIF_RELATED_SUCCESS = 'FETCHING_GIF_RELATED_SUCCESS';
export const FETCHING_GIF_RELATED_FAILURE = 'FETCHING_GIF_RELATED_FAILURE';
export const FETCHING_GIF_RELATED_MORE = 'FETCHING_GIF_RELATED_MORE';
export const FETCHING_GIF_RELATED_MORE_SUCCESS = 'FETCHING_GIF_RELATED_MORE_SUCCESS';
export const FETCHING_GIF_RELATED_MORE_FAILURE = 'FETCHING_GIF_RELATED_MORE_FAILURE';

export const FETCHING_GIF_AUTOCOMPLETE = 'FETCHING_GIF_AUTOCOMPLETE';
export const FETCHING_GIF_AUTOCOMPLETE_SUCCESS = 'FETCHING_GIF_AUTOCOMPLETE_SUCCESS';
export const FETCHING_GIF_AUTOCOMPLETE_FAILURE = 'FETCHING_GIF_AUTOCOMPLETE_FAILURE';


export const FETCHING_GIF_DATA_MORE = 'FETCHING_GIF_DATA_MORE';
export const FETCHING_GIF_DATA_MORE_SUCCESS = 'FETCHING_GIF_DATA_MORE_SUCCESS';
export const FETCHING_GIF_DATA_MORE_FAILURE = 'FETCHING_GIF_DATA_MORE_FAILURE';
